// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::drivetrainSpeedController1 = NULL;
SpeedController* RobotMap::drivetrainSpeedController2 = NULL;
RobotDrive* RobotMap::drivetrainRobotDrive2 = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	drivetrainSpeedController1 = new Jaguar(1, 1);
	lw->AddActuator("Drivetrain", "Speed Controller 1", (Jaguar*) drivetrainSpeedController1);
	
	drivetrainSpeedController2 = new Jaguar(1, 2);
	lw->AddActuator("Drivetrain", "Speed Controller 2", (Jaguar*) drivetrainSpeedController2);
	
	drivetrainRobotDrive2 = new RobotDrive(drivetrainSpeedController1, drivetrainSpeedController2);
	
	drivetrainRobotDrive2->SetSafetyEnabled(true);
        drivetrainRobotDrive2->SetExpiration(0.1);
        drivetrainRobotDrive2->SetSensitivity(0.5);
        drivetrainRobotDrive2->SetMaxOutput(1.0);
        


	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
